version: 2
updates:
  - package-ecosystem: "npm" # ここは npm のまま
    directory: "/" # あなたのプロジェクトのルートディレクトリ
    schedule:
      interval: "daily"
    # pnpm-lock.yaml を使用するように dependabot に指示
    ignore:
      - dependency-name: "*"
        versions: ["< pnpm-lock.yaml"]
